### ISSUE TITLE
meld:keyup interferes with meld:model.defer

### ISSUE THREAD

**Issue by eruvanos** [mikeabrahamsen/Flask-Meld#17]
## Issue

Combine `meld:keyup` with `meld:model.defer`, every keyup event does trigger the action listener and queues a `syncInput` event.

## Code References

`flask_meld/static/js/component.js:105`

### Template

```
    <div class="row">
        <input type="text" meld:model.defer="text" meld:keyup.enter="add" autofocus>
    </div>
```

### Component
```
class Todos(Component):
    text = ''

    def add(self):
        print(self.text)
        self.text=""
```

**Comment by mikeabrahamsen** [comment]
fixed with 511e3f97e300d2a4227b7478ca3a856c379ffa3f and 9507fd1dd340a1ea03d755914f9ccd2b8c884e6d
