### ISSUE TITLE
model value not updated with defer

### ISSUE THREAD

**Issue by eruvanos** [mikeabrahamsen/Flask-Meld#18]
## Issue

Using model with defer the html representation does not update

## Code References

`flask_meld/static/js/component.js:105`

## Reproduce

* Type some text
* Click on the add button
* ⚡️ text should be empty but the browser still shows text

### Template

```
    <div class="row">
        <input type="text" meld:model.defer="text" autofocus>
        <button meld:click="add">+</button>
    </div>
```

### Component
```
class Todos(Component):
    text = ''

    def add(self):
        print(self.text)
        self.text=""
```

**Comment by mikeabrahamsen** [comment]
fixed with 511e3f97e300d2a4227b7478ca3a856c379ffa3f
