### ISSUE TITLE
Missing Source Maps

### ISSUE THREAD

**Issue by kaidamasaki** [mikeabrahamsen/Flask-Meld#19]
In the web console I get the following error:

```
Source map error: Error: request failed with status 404
Resource URL: http://localhost:5000/meld_js_src/socket.io.js
Source Map URL: socket.io.min.js.map
```

Poking at things it looks like `socket.io.js` is included inside of `meld_js_src` but not `socket.io.js.map`.

**Comment by mikeabrahamsen** [comment]
closed via f31c1ad877ca7c0625dd8e23f1f6db46f6be5458
