### ISSUE TITLE
Add documentation to README about passing variables from Jinja Template to Meld Component

### ISSUE THREAD

**Issue by edmondchuc** [mikeabrahamsen/Flask-Meld#20]
Example: 
```
{% with movie=movie %}
    {% meld 'watchlist_buttons' %}
{% endwith %}
```

Make the `movie` variable available in the meld template?

What I'm trying to achieve is I have a list of movies. I want to be able to press the "add to watchlist" button and add it to the database. But to achieve this, my meld template needs the context of what movie it is when the user presses the "add to watchlist" button.

What is the correct way of passing data from the frontend to the backend? I've seen in the flask-meld.dev website that you bind the input with `meld:model`. However, when I try this but combine it with Jinja2, it doesn't work. 

```
<div class="clear">
    <input type="text" meld:model="title" value="Captain America"></input>
    <a meld:click="add_to_watchlist" class="btn btn-primary mt-2">Add to watchlist</a>
    <a meld:click="add_to_watched" href="#" class="btn btn-light mt-2">Add to watched</a>
</div>
```

A good way to explain what I'm trying to achieve is, on the flask-meld.dev website, in the search example, is it possible for the backend to check and determine which person the user clicked on? For example, if the user searches "Pammie", and they click on the box (imagine they can click on it).

Any help would be appreciated.

**Comment by edmondchuc** [comment]
@mikeabrahamsen thank you very much for your response. I will try your solution later this week. 👍

**Comment by mikeabrahamsen** [comment]
This is a great issue for a beginner. 
Work through the example in the comment to understand how it works.

Take a look at the code highlighted below to see how a "Meld" template tag passes **kwargs to the component render function:
First, the Meld Tag is defined:
https://github.com/mikeabrahamsen/Flask-Meld/blob/b136e32840c4dca665f2a36f662ede652c70e6f8/flask_meld/tag.py#L8-L13
Second, the Component class is found based on the Meld Tag and the keyword arguments are passed through to the component:
https://github.com/mikeabrahamsen/Flask-Meld/blob/b136e32840c4dca665f2a36f662ede652c70e6f8/flask_meld/tag.py#L50-L59

**Comment by mikeabrahamsen** [comment]
Thanks @olierxleben
