### ISSUE TITLE
Add a CLI command to create a new component

### ISSUE THREAD

**Issue by mikeabrahamsen** [mikeabrahamsen/Flask-Meld#24]
Currently the CLI has the ability to scaffold a project for you. Let's add a shortcut that will allow the CLI to create a new component. This will take a `name` argument and create a meld `template` file and corresponding `component` file

**Comment by RusinR** [comment]
Submitted PR https://github.com/mikeabrahamsen/Flask-Meld/pull/28.

**Comment by mikeabrahamsen** [comment]
closed with 70b8ed83d87042ea3ecb4f665da0b13c1b397b7f
