### ISSUE TITLE
Component template top comment makes component disappear

### ISSUE THREAD

**Issue by itmgrnph** [mikeabrahamsen/Flask-Meld#50]
I tried your 'counter' example from the blog. Every time I click add/subtract buttons, the component disappears from the screen. I checked on the dev screen. Every time it keeps the component's comment and the rest of the component HTML disappears. I removed the components' top comment  and it started to work. Please investigate.

**Comment by itmgrnph** [comment]
<pre>(.env) <font color="#33DA7A"><b>crysanthus@crysanthus-dev</b></font>:<font color="#2A7BDE"><b>~/nphapps/ratr</b></font>$ pip freeze
beautifulsoup4==4.10.0
bidict==0.21.4
click==7.1.2
dnspython==2.1.0
email-validator==1.1.3
eventlet==0.33.0
Flask==2.0.2
Flask-Login==0.5.0
Flask-Meld==0.13.1
Flask-SocketIO==5.1.1
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.0
gevent==21.12.0
gevent-websocket==0.10.1
greenlet==1.1.2
gunicorn==20.1.0
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
jinja2-simple-tags==0.3.1
MarkupSafe==2.0.1
orjson==3.6.5
pkg_resources==0.0.0
python-engineio==4.3.0
python-socketio==5.5.0
six==1.16.0
soupsieve==2.3.1
SQLAlchemy==1.4.28
Werkzeug==2.0.2
WTForms==3.0.0
zope.event==4.5.0
zope.interface==5.4.0
</pre>

**Comment by itmgrnph** [comment]
<pre>(.env) <font color="#33DA7A"><b>crysanthus@crysanthus-dev</b></font>:<font color="#2A7BDE"><b>~/nphapps/ratr</b></font>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
(.env) <font color="#33DA7A"><b>crysanthus@crysanthus-dev</b></font>:<font color="#2A7BDE"><b>~/nphapps/ratr</b></font>$ uname -a
Linux crysanthus-dev 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(.env) <font color="#33DA7A"><b>crysanthus@crysanthus-dev</b></font>:<font color="#2A7BDE"><b>~/nphapps/ratr</b></font>$ 
</pre>

**Comment by mikeabrahamsen** [comment]
Thank you! This is a known bug #27. I'll update the article to remove the comment to help reduce the number of occurrences until the bug is fixed.
